### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [gnitetsky/grid-template-init-project#1]
цвет не соответствует
![image](https://user-images.githubusercontent.com/8464662/54713015-4d708080-4b56-11e9-99b7-28cc631a088a.png)
![image](https://user-images.githubusercontent.com/8464662/54713052-611be700-4b56-11e9-9c5a-ad7e56d39b8e.png)

**Comment by gnitetsky** [comment]
changed background-color in footer, changed style input
